/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "ControlModule.h"

int main(void) {

	ControlModule MAX7219 = ControlModule(SPI1);

	Led RedLed, GreenLed;
	RedLed.Config(GPIOB, 13);
	GreenLed.Config(GPIOC, 8);

	GreenLed.SetState(LED_ON);
	RedLed.SetState(LED_ON);

	Button UpButton, DownButton;
	UpButton.Config(GPIOA, 8);
	DownButton.Config(GPIOF, 7);

	if (UpButton.GetState() == PRESSED)
		RedLed.SetState(LED_OFF);

	if (DownButton.GetState() == PRESSED)
		GreenLed.SetState(LED_OFF);

	Buzzer Beeper;
	Beeper.Config(GPIOA, 12);
	Beeper.SetState(ON);
	Beeper.SetState(OFF);

	/* Loop forever */
	for (;;)
		;
}
